@echo off
cd /d "%~dp0"
echo Menginisialisasi Git di folder %CD%...
git init
echo Menambahkan file...
git add .
echo Melakukan commit...
git commit -m "Submit all lab answers and documentation (Force Push)"
echo Menghubungkan ke repository...
git remote add origin https://github.com/ahmadhelmiafandi/devops-capstone-project.git
git remote set-url origin https://github.com/ahmadhelmiafandi/devops-capstone-project.git
echo Mengatur branch ke main...
git branch -M main
echo Melakukan FORCE push ke GitHub...
git push -f -u origin main
echo.
echo Selesai! Silakan cek repository Anda.
pause
